# name of your github action
name: ElectronBuilder
# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the main branch
      - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: see directory
        run: ls
  build_on_win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/github-actions
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: see directory
        run: ls
