# name of your github action
name: ElectronBuilder
# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the main branch
      - main
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build App
        run: yarn dist:mac
      - name: see directory
        run: ls
      - name: see dist directory
        run: ls dist/

  build_on_win:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: install node tools
        run: npm install --global --production windows-build-tools@4.0.0
      - name: install node-gyp
        run: npm install --global node-gyp@latest
      - name: Set node config to use python2.7
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2015
        run: npm config set msvs_version 2015
      - name: Work around for Windows Server 2019
        run: set path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin
      - name: Install dependencies
        run: yarn install
      - name: Build on Windows
        run: yarn dist:win
      - name: see directory
        run: ls
